allowBuilds:
  '@parcel/watcher': true
  'sharp': true

overrides:
  'sharp-ico@0.1.5>sharp': '0.33.5'
  'element-plus@2.14.2>@vueuse/core': '14.4.0'

packages:
  - 'apps/*'
  - 'packages/*'

catalog:
  'npm-run-all2': ^9.0.2
